// One-shot: bundle the design-system webfonts locally so the iOS build works
// offline and Cyrillic (RU) renders. Pulls Manrope + JetBrains Mono woff2 from
// Google Fonts (latin + latin-ext + cyrillic subsets), writes public/fonts/*
// and a generated src/fonts.css with rewritten @font-face rules.
// Run once: `node scripts/fetch-fonts.mjs`. Not part of the build.
import { mkdir, writeFile } from "node:fs/promises";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const WANT = new Set(["latin", "latin-ext", "cyrillic", "cyrillic-ext"]);

const FAMILIES = [
  "Manrope:wght@400;500;600;700;800",
  "JetBrains+Mono:wght@400;500;700",
];

const OUT_DIR = "public/fonts";
await mkdir(OUT_DIR, { recursive: true });

const faces = [];

for (const spec of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`;
  const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();
  // Google emits: /* subset */\n@font-face{...src:url(..woff2) format('woff2');..}
  const blocks = css.split("/*").slice(1);
  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf("*/")).trim();
    if (!WANT.has(subset)) continue;
    const block = raw.slice(raw.indexOf("@font-face"));
    const fam = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? "400";
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? "normal";
    const range = /unicode-range:\s*([^;]+)/.exec(block)?.[1]?.trim() ?? "";
    const src = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
    if (!fam || !src) continue;
    const slug = `${fam.replace(/\s+/g, "")}-${weight}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(src, { headers: { "User-Agent": UA } })).arrayBuffer());
    await writeFile(`${OUT_DIR}/${slug}`, buf);
    faces.push(
      `@font-face {\n` +
        `  font-family: '${fam}';\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${slug}') format('woff2');\n` +
        `  unicode-range: ${range};\n}`,
    );
    console.log(`✓ ${slug} (${buf.length} B)`);
  }
}

const header =
  "/* Generated by scripts/fetch-fonts.mjs — bundled webfonts for offline iOS.\n" +
  "   Manrope (body) + JetBrains Mono (labels/numbers), latin + cyrillic. */\n\n";
await writeFile("src/fonts.css", header + faces.join("\n\n") + "\n");
console.log(`\nWrote src/fonts.css with ${faces.length} @font-face rules.`);
